version: '3.8'

services:
  bun:
    container_name: bun
    build:
      context: ./backend
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
    env_file:
      - ./backend/.env
    depends_on: 
      - mongo
      - minio
  mongo:
    container_name: mongo
    build:
      context: ./database
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./database/data/:/data/db/
  minio:
    container_name: minio
    build:
      context: ./storage
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./storage/data:/data
