import { del, get, set, update } from "idb-keyval";
import subjects from "../utils/subjects";
import {
  addDays,
  endOfMonth,
  endOfWeek,
  format,
  getDay,
  getWeek,
  isSameMonth,
  isToday,
  startOfMonth,
  startOfWeek,
} from "date-fns";
import { getAttendanceCalendar } from "../utils/calender";

export const doubtsProvider: Provider<{ doubts: Doubt[] }> = {
  data: { doubts: [] },
  initial: true,
  async load({ date }: { date: Date}) {
    const data = {
      doubts: [
        {
          uid: "DO12345",
          title: "Algebraic Equations Doubt",
          respondants: 8,
          subject: 18,
          by: {
            userId: "user_1",
            firstName: "John",
            lastName: "Doe",
            phoneNumber: "+12345678901",
            meta: {},
            token: "token_1",
          },
          description:
            "\n            <p>I'm struggling to solve algebraic equations involving variables. Can someone help me understand the process step-by-step?</p>\n          ",
          cover: "https://picsum.photos/200",
          date: new Date("2024-05-18T16:23:56.739Z"),
        },
        {
          uid: "DO12346",
          title: "Chemical Reactions Doubt",
          respondants: 12,
          subject: 16,
          by: {
            userId: "user_2",
            firstName: "Jane",
            lastName: "Doe",
            phoneNumber: "+12345678902",
            meta: {},
            token: "token_2",
          },
          description:
            "\n            <p>I need clarification on balancing chemical equations. Can someone explain the rules and provide examples?</p>\n          ",
          cover: "https://picsum.photos/300",
          date: new Date("2024-06-07T23:52:11.210Z"),
        },
        {
          uid: "DO12347",
          title: "Literature Analysis Doubt",
          respondants: 5,
          subject: 2,
          by: {
            userId: "user_3",
            firstName: "Alice",
            lastName: "Smith",
            phoneNumber: "+12345678903",
            meta: {},
            token: "token_3",
          },
          description:
            "\n            <p>I'm having trouble analyzing poems for my literature class. Can someone guide me on identifying poetic devices and themes?</p>\n          ",
          cover: "https://picsum.photos/400",
          date: new Date("2024-05-23T17:34:05.482Z"),
        },
        {
          uid: "DO12348",
          title: "World War II Causes Doubt",
          respondants: 9,
          subject: 0,
          by: {
            userId: "user_4",
            firstName: "Bob",
            lastName: "Johnson",
            phoneNumber: "+12345678904",
            meta: {},
            token: "token_4",
          },
          description:
            "\n            <p>I am confused about the main causes of World War II. Can someone explain the political and economic factors involved?</p>\n          ",
          cover: "https://picsum.photos/500",
          date: new Date("2024-05-17T21:18:46.930Z"),
        },
        {
          uid: "DO12349",
          title: "Philosophical Theories Doubt",
          respondants: 7,
          subject: 1,
          by: {
            userId: "user_5",
            firstName: "Eva",
            lastName: "Brown",
            phoneNumber: "+12345678905",
            meta: {},
            token: "token_5",
          },
          description:
            "\n            <p>I am struggling to understand different philosophical theories. Can someone explain existentialism and its main proponents?</p>\n          ",
          cover: "https://picsum.photos/600",
          date: new Date("2024-05-20T09:49:23.244Z"),
        },
        {
          uid: "DO12350",
          title: "Language Learning Techniques Doubt",
          respondants: 10,
          subject: 3,
          by: {
            userId: "user_6",
            firstName: "Mike",
            lastName: "Davis",
            phoneNumber: "+12345678906",
            meta: {},
            token: "token_6",
          },
          description:
            "\n            <p>What are some effective techniques for learning new languages? I am particularly interested in methods for memorizing vocabulary.</p>\n          ",
          cover: "https://picsum.photos/700",
          date: new Date("2024-06-11T17:55:03.751Z"),
        },
        {
          uid: "DO12351",
          title: "Art Styles Doubt",
          respondants: 6,
          subject: 5,
          by: {
            userId: "user_7",
            firstName: "Sara",
            lastName: "Wilson",
            phoneNumber: "+12345678907",
            meta: {},
            token: "token_7",
          },
          description:
            "\n            <p>I am trying to differentiate between various art styles such as Baroque and Rococo. Can someone provide key characteristics of each?</p>\n          ",
          cover: "https://picsum.photos/800",
          date: new Date("2024-06-09T01:11:56.812Z"),
        },
        {
          uid: "DO12352",
          title: "Psychological Concepts Doubt",
          respondants: 11,
          subject: 6,
          by: {
            userId: "user_8",
            firstName: "Chris",
            lastName: "Taylor",
            phoneNumber: "+12345678908",
            meta: {},
            token: "token_8",
          },
          description:
            "\n            <p>I need help understanding various psychological concepts, especially the different types of conditioning in behaviorism.</p>\n          ",
          cover: "https://picsum.photos/900",
          date: new Date("2024-05-19T12:02:57.382Z"),
        },
        {
          uid: "DO12353",
          title: "Sociological Theories Doubt",
          respondants: 8,
          subject: 7,
          by: {
            userId: "user_9",
            firstName: "Lily",
            lastName: "Martinez",
            phoneNumber: "+12345678909",
            meta: {},
            token: "token_9",
          },
          description:
            "\n            <p>I am struggling to grasp the different sociological theories. Can someone explain the key differences between functionalism and conflict theory?</p>\n          ",
          cover: "https://picsum.photos/1000",
          date: new Date("2024-05-31T04:17:28.711Z"),
        },
        {
          uid: "DO12354",
          title: "Political Systems Doubt",
          respondants: 10,
          subject: 9,
          by: {
            userId: "user_10",
            firstName: "Tom",
            lastName: "Clark",
            phoneNumber: "+12345678910",
            meta: {},
            token: "token_10",
          },
          description:
            "\n            <p>Can someone help me understand the differences between various political systems such as democracy and authoritarianism?</p>\n          ",
          cover: "https://picsum.photos/1100",
          date: new Date("2024-05-30T21:09:10.069Z"),
        },
        {
          uid: "DO12355",
          title: "Economic Principles Doubt",
          respondants: 7,
          subject: 10,
          by: {
            userId: "user_11",
            firstName: "James",
            lastName: "Anderson",
            phoneNumber: "+12345678911",
            meta: {},
            token: "token_11",
          },
          description:
            "\n            <p>I need a better understanding of basic economic principles, particularly the concept of supply and demand.</p>\n          ",
          cover: "https://picsum.photos/1200",
          date: new Date("2024-05-29T01:22:24.043Z"),
        },
        {
          uid: "DO12356",
          title: "Geographical Mapping Doubt",
          respondants: 6,
          subject: 11,
          by: {
            userId: "user_12",
            firstName: "Laura",
            lastName: "Thomas",
            phoneNumber: "+12345678912",
            meta: {},
            token: "token_12",
          },
          description:
            "\n            <p>How do I accurately map geographical features such as mountains and rivers? Are there specific techniques or tools recommended?</p>\n          ",
          cover: "https://picsum.photos/1300",
          date: new Date("2024-06-06T13:56:00.791Z"),
        },
        {
          uid: "DO12357",
          title: "Educational Theories Doubt",
          respondants: 5,
          subject: 12,
          by: {
            userId: "user_13",
            firstName: "Sophia",
            lastName: "Lee",
            phoneNumber: "+12345678913",
            meta: {},
            token: "token_13",
          },
          description:
            "\n            <p>I am studying different educational theories. Can someone explain the main ideas behind constructivism and how it differs from traditional learning models?</p>\n          ",
          cover: "https://picsum.photos/1400",
          date: new Date("2024-06-14T21:06:11.497Z"),
        },
        {
          uid: "DO12358",
          title: "Legal Systems Doubt",
          respondants: 8,
          subject: 13,
          by: {
            userId: "user_14",
            firstName: "Henry",
            lastName: "Walker",
            phoneNumber: "+12345678914",
            meta: {},
            token: "token_14",
          },
          description:
            "\n            <p>Can someone explain the differences between common law and civil law systems? What are the main advantages and disadvantages of each?</p>\n          ",
          cover: "https://picsum.photos/1500",
          date: new Date("2024-06-08T22:32:42.668Z"),
        },
        {
          uid: "DO12359",
          title: "Physics Concepts Doubt",
          respondants: 12,
          subject: 14,
          by: {
            userId: "user_15",
            firstName: "Olivia",
            lastName: "Martinez",
            phoneNumber: "+12345678915",
            meta: {},
            token: "token_15",
          },
          description:
            "\n            <p>I am having trouble understanding the concepts of relativity in physics. Can someone explain Einstein's theory in simple terms?</p>\n          ",
          cover: "https://picsum.photos/1600",
          date: new Date("2024-05-21T20:42:36.841Z"),
        },
        {
          uid: "DO12360",
          title: "Biological Processes Doubt",
          respondants: 9,
          subject: 17,
          by: {
            userId: "user_16",
            firstName: "Emma",
            lastName: "Roberts",
            phoneNumber: "+12345678916",
            meta: {},
            token: "token_16",
          },
          description:
            "\n            <p>Can someone help me understand the process of photosynthesis? I need a detailed explanation of the steps involved.</p>\n          ",
          cover: "https://picsum.photos/1700",
          date: new Date("2024-05-18T13:28:33.567Z"),
        },
        {
          uid: "DO12361",
          title: "Earth Sciences Doubt",
          respondants: 7,
          subject: 18,
          by: {
            userId: "user_17",
            firstName: "Lucas",
            lastName: "Miller",
            phoneNumber: "+12345678917",
            meta: {},
            token: "token_17",
          },
          description:
            "\n            <p>I am confused about the different types of rocks and how they are formed. Can someone explain the rock cycle in detail?</p>\n          ",
          cover: "https://picsum.photos/1800",
          date: new Date("2024-05-22T08:02:18.508Z"),
        },
        {
          uid: "DO12362",
          title: "Computer Programming Doubt",
          respondants: 15,
          subject: 19,
          by: {
            userId: "user_18",
            firstName: "David",
            lastName: "Harris",
            phoneNumber: "+12345678918",
            meta: {},
            token: "token_18",
          },
          description:
            "\n            <p>Can someone explain how to write a basic program in Python? I am new to programming and need a step-by-step guide.</p>\n          ",
          cover: "https://picsum.photos/1900",
          date: new Date("2024-06-12T09:04:08.361Z"),
        },
        {
          uid: "DO12363",
          title: "Engineering Principles Doubt",
          respondants: 6,
          subject: 20,
          by: {
            userId: "user_19",
            firstName: "Daniel",
            lastName: "Wilson",
            phoneNumber: "+12345678919",
            meta: {},
            token: "token_19",
          },
          description:
            "\n            <p>What are the fundamental principles of electrical engineering? I need help understanding Ohm's Law and its applications.</p>\n          ",
          cover: "https://picsum.photos/2000",
          date: new Date("2024-06-06T17:49:42.991Z"),
        },
        {
          uid: "DO12364",
          title: "Medical Terminology Doubt",
          respondants: 8,
          subject: 21,
          by: {
            userId: "user_20",
            firstName: "Amy",
            lastName: "White",
            phoneNumber: "+12345678920",
            meta: {},
            token: "token_20",
          },
          description:
            "\n            <p>I am struggling with medical terminology. Can someone explain the meanings of common prefixes and suffixes used in medical terms?</p>\n          ",
          cover: "https://picsum.photos/2100",
          date: new Date("2024-06-13T05:54:10.730Z"),
        },
        {
          uid: "DO12365",
          title: "Health Sciences Doubt",
          respondants: 10,
          subject: 22,
          by: {
            userId: "user_21",
            firstName: "Ella",
            lastName: "King",
            phoneNumber: "+12345678921",
            meta: {},
            token: "token_21",
          },
          description:
            "\n            <p>What are the best practices for maintaining a healthy lifestyle? I need information on diet, exercise, and mental health.</p>\n          ",
          cover: "https://picsum.photos/2200",
          date: new Date("2024-05-31T17:56:59.748Z"),
        },
        {
          uid: "DO12366",
          title: "Environmental Science Doubt",
          respondants: 9,
          subject: 23,
          by: {
            userId: "user_22",
            firstName: "Grace",
            lastName: "Wright",
            phoneNumber: "+12345678922",
            meta: {},
            token: "token_22",
          },
          description:
            "\n            <p>Can someone explain the impact of human activities on climate change? I need detailed information on greenhouse gases and global warming.</p>\n          ",
          cover: "https://picsum.photos/2300",
          date: new Date("2024-05-29T19:36:21.174Z"),
        },
      ],
    };

    doubtsProvider.initial = false;
    doubtsProvider.data = data;
  },
};
