export const performanceProvider: Provider<{
  scores: ScoresPerformanceRef[];
  attendance: AttendancePerformanceRef[];
  overall?: number;
}> = {
  data: {
    scores: [],
    attendance: [],
    overall: undefined,
  },
  initial: true,
  async load() {
    const data = {
      scores: [
        {
          english: 78,
          hindi: 65,
          marathi: 89,
          maths: 95,
          science: 74,
          history: 83,
          geography: 91,
          month: "January",
        },
        {
          english: 88,
          hindi: 79,
          marathi: 67,
          maths: 85,
          science: 72,
          history: 91,
          geography: 78,
          month: "February",
        },
        {
          english: 94,
          hindi: 84,
          marathi: 88,
          maths: 91,
          science: 76,
          history: 85,
          geography: 93,
          month: "March",
        },
        {
          english: 81,
          hindi: 73,
          marathi: 92,
          maths: 87,
          science: 82,
          history: 77,
          geography: 89,
          month: "April",
        },
        {
          english: 87,
          hindi: 76,
          marathi: 84,
          maths: 90,
          science: 78,
          history: 83,
          geography: 80,
          month: "May",
        },
        {
          english: 93,
          hindi: 88,
          marathi: 81,
          maths: 92,
          science: 85,
          history: 79,
          geography: 95,
          month: "June",
        },
        {
          english: 85,
          hindi: 77,
          marathi: 86,
          maths: 89,
          science: 80,
          history: 92,
          geography: 88,
          month: "July",
        },
        {
          english: 89,
          hindi: 90,
          marathi: 79,
          maths: 86,
          science: 91,
          history: 87,
          geography: 82,
          month: "August",
        },
        {
          english: 91,
          hindi: 85,
          marathi: 83,
          maths: 94,
          science: 88,
          history: 81,
          geography: 90,
          month: "September",
        },
        {
          english: 84,
          hindi: 78,
          marathi: 90,
          maths: 88,
          science: 75,
          history: 86,
          geography: 89,
          month: "October",
        },
        {
          english: 92,
          hindi: 81,
          marathi: 87,
          maths: 93,
          science: 79,
          history: 84,
          geography: 91,
          month: "November",
        },
        {
          english: 86,
          hindi: 80,
          marathi: 94,
          maths: 89,
          science: 77,
          history: 82,
          geography: 90,
          month: "December",
        },
      ],
      attendance: [
        {
          present: 23,
          absent: 4,
          month: "January",
        },
        {
          present: 25,
          absent: 2,
          month: "February",
        },
        {
          present: 24,
          absent: 3,
          month: "March",
        },
        {
          present: 22,
          absent: 5,
          month: "April",
        },
        {
          present: 26,
          absent: 1,
          month: "May",
        },
        {
          present: 27,
          absent: 0,
          month: "June",
        },
        {
          present: 21,
          absent: 6,
          month: "July",
        },
        {
          present: 24,
          absent: 3,
          month: "August",
        },
        {
          present: 23,
          absent: 4,
          month: "September",
        },
        {
          present: 25,
          absent: 2,
          month: "October",
        },
        {
          present: 22,
          absent: 5,
          month: "November",
        },
        {
          present: 26,
          absent: 1,
          month: "December",
        },
      ],
      overall: 86,
    };

    performanceProvider.initial = false;
    performanceProvider.data = data;
  },
};
