import { del, get, set, update } from "idb-keyval";
import subjects from "../utils/subjects";

export const resourcesProvider: Provider<{ files: _File[] }> = {
  data: { files: [] },
  initial: true,
  async load() {
    const data: { files: _File[] } = {
      files: [
        {
          _id: "1",
          url: "http://example.com/Biology_Notes_Chapter1.pdf",
          size: "1.2MB",
          type: "application/pdf",
          title: "Biology Notes",
          name: "Biology_Notes_Chapter1.pdf",
          date: new Date("2023-06-01T00:00:00.000Z"),
          icon: "image",
          by: { firstName: "Ms. Thompson" },
        },
        {
          _id: "2",
          url: "http://example.com/Algebra_Workbook_Exercises.docx",
          size: "850KB",
          type: "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
          title: "Algebra Workbook",
          name: "Algebra_Workbook_Exercises.docx",
          date: new Date("2023-06-02T00:00:00.000Z"),
          icon: "picture_as_pdf",
          by: { firstName: "Mr. Adams" },
        },
        {
          _id: "3",
          url: "http://example.com/World_History_Timeline.pptx",
          size: "2.5MB",
          type: "application/vnd.openxmlformats-officedocument.presentationml.presentation",
          title: "World History Timeline",
          name: "World_History_Timeline.pptx",
          date: new Date("2023-06-03T00:00:00.000Z"),
          icon: "image",
          by: { firstName: "Mr. Brown" },
        },
        {
          _id: "4",
          url: "http://example.com/Chemistry_Lab_Report_Template.docx",
          size: "400KB",
          type: "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
          title: "Chemistry Lab Report",
          name: "Chemistry_Lab_Report_Template.docx",
          date: new Date("2023-06-04T00:00:00.000Z"),
          icon: "folder_zip",
          by: { firstName: "Ms. Garcia" },
        },
        {
          _id: "5",
          url: "http://example.com/Literature_Reading_List_Semester1.pdf",
          size: "200KB",
          type: "application/pdf",
          title: "Literature Reading List",
          name: "Literature_Reading_List_Semester1.pdf",
          date: new Date("2023-06-05T00:00:00.000Z"),
          icon: "folder_zip",
          by: { firstName: "Mrs. Davis" },
        },
        {
          _id: "6",
          url: "http://example.com/Geometry_Practice_Problems.pdf",
          size: "1.0MB",
          type: "application/pdf",
          title: "Geometry Practice Problems",
          name: "Geometry_Practice_Problems.pdf",
          date: new Date("2023-06-06T00:00:00.000Z"),
          icon: "picture_as_pdf",
          by: { firstName: "Mr. Harris" },
        },
        {
          _id: "7",
          url: "http://example.com/Physics_Equations_Sheet.pdf",
          size: "150KB",
          type: "application/pdf",
          title: "Physics Equations Sheet",
          name: "Physics_Equations_Sheet.pdf",
          date: new Date("2023-06-07T00:00:00.000Z"),
          icon: "description",
          by: { firstName: "Ms. Lee" },
        },
        {
          _id: "8",
          url: "http://example.com/Spanish_Vocabulary_List.docx",
          size: "300KB",
          type: "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
          title: "Spanish Vocabulary List",
          name: "Spanish_Vocabulary_List.docx",
          date: new Date("2023-06-08T00:00:00.000Z"),
          icon: "description",
          by: { firstName: "Mr. Martinez" },
        },
        {
          _id: "9",
          url: "http://example.com/Art_History_Essay_Guidelines.pdf",
          size: "500KB",
          type: "application/pdf",
          title: "Art History Essay Guidelines",
          name: "Art_History_Essay_Guidelines.pdf",
          date: new Date("2023-06-09T00:00:00.000Z"),
          icon: "folder_zip",
          by: { firstName: "Mrs. Robinson" },
        },
        {
          _id: "10",
          url: "http://example.com/Computer_Science_Project_Outline.pptx",
          size: "1.8MB",
          type: "application/vnd.openxmlformats-officedocument.presentationml.presentation",
          title: "Computer Science Project Outline",
          name: "Computer_Science_Project_Outline.pptx",
          date: new Date("2023-06-10T00:00:00.000Z"),
          icon: "image",
          by: { firstName: "Mr. Evans" },
        },
      ],
    };

    resourcesProvider.initial = false;
    resourcesProvider.data = data;
  },
};
