# Use the official MongoDB image from the Docker Hub
FROM mongo:latest

# Set environment variables for MongoDB
ENV MONGO_INITDB_ROOT_USERNAME=pradyut
ENV MONGO_INITDB_ROOT_PASSWORD=das

# Expose MongoDB port
EXPOSE 27017

# Command to run MongoDB
CMD ["mongod"]
